# Generated by Django 3.2.13 on 2022-05-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
                ('cathedra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassesTask',
            fields=[
                ('classes_task_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_pk', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('task_text', models.TextField()),
                ('max_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_full_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('workload_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.classes')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('student_classes_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradedTask',
            fields=[
                ('graded_task_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('class_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.classestask')),
                ('graded_by_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.teacher')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.student')),
            ],
        ),
        migrations.AddField(
            model_name='classestask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesUI.task'),
        ),
    ]
