# Generated by Django 3.2.13 on 2022-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesUI', '0002_auto_20220519_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_full_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
